'use client'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import type { HQLink, HQNote, HQTask } from '@/lib/hq-types'
import { formatDate, kindNames, priorityNames, projectNames, relationNames, safeEvidenceUrl, safeExternalUrl, statusNames, type GraphItem } from './hq-data'
import { useHQResource } from './use-hq-resource'
import { EvidenceForm } from './evidence-form'
import { markdownBody } from './note-presentation'
import styles from './headquarters.module.css'
export function KnowledgeInspector({ selected, item, items, links, refresh, onSelect, onCreate, onOpenTask, onRefresh }: { selected: string | null; item?: GraphItem; items: GraphItem[]; links: HQLink[]; refresh: number; onSelect: (id: string) => void; onCreate: (note?: HQNote) => void; onOpenTask: (task: HQTask) => void; onRefresh: () => void }) {
  const noteResource = useHQResource<{ note: HQNote; content: string }>(selected && !selected.startsWith('task:') ? `/api/headquarters/knowledge?id=${encodeURIComponent(selected)}` : null, refresh)
  const note = noteResource.data?.note || item?.note
  const task = item?.task
  const relations = links.filter(link => link.source === selected || link.target === selected)
  return <aside className={`${styles.card} ${styles.inspector}`} aria-label="Kilde og beslutningsgrunnlag" aria-busy={noteResource.loading}>
    <div className={styles.cardHead}><div><span className={styles.overline}>Grunnlaget for handling</span><h2>{task ? 'Oppgave og resultat' : 'Kildeinspektør'}</h2></div><span className={styles.inspectorMark} aria-hidden="true">↗</span></div>
    {!selected ? <div className={styles.empty}><strong>Begynn med en kilde</strong><p>Velg et dokument i grafen eller en oppgave. Her kan du lese innholdet, følge relasjonene og opprette et konkret tiltak.</p></div> : <div className={styles.inspectorBody}>
      {task ? <><div className={styles.metaLine}><span>{projectNames[task.projectKey]}</span><span className={styles.tag}>{task.ticketRef || `MC #${task.id}`}</span></div><h3 className={styles.inspectorTitle}>{task.title}</h3><div className={styles.metaLine}><span>{statusNames[task.status] || task.status}</span><span>{priorityNames[task.priority] || task.priority} prioritet</span></div><p className={styles.muted}>{task.description || 'Ingen beskrivelse registrert.'}</p><dl className={styles.detailList}><div><dt>Sist endret</dt><dd>{formatDate(task.updatedAt)}</dd></div><div><dt>Ansvarlig</dt><dd>{task.assignedTo || 'Ikke tildelt'}</dd></div><div><dt>Forventet resultat</dt><dd>{task.expectedOutcome || 'Forventet resultat er ikke definert.'}</dd></div></dl><div className={styles.detailSection}><h4>Godkjenningskrav</h4>{task.acceptanceCriteria.length ? <ul>{task.acceptanceCriteria.map((criterion, index) => <li key={index}>{criterion}</li>)}</ul> : <p className={styles.muted}>Ingen etterprøvbare krav er registrert.</p>}</div><div className={styles.detailSection}><h4>Bevis og måling</h4><span className={task.measurementStatus === 'observed' ? styles.good : styles.warning}>{task.measurementStatus === 'observed' ? 'Observasjon registrert' : 'Effekt er ikke målt'}</span>{task.evidence.length ? task.evidence.map((evidence, index) => <article className={styles.evidenceItem} key={index}><strong>{evidence.label}</strong>{evidence.detail && <p>{evidence.detail}</p>}{safeEvidenceUrl(evidence.url) && <a href={safeEvidenceUrl(evidence.url)} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer">Åpne bevis ↗</a>}{evidence.createdAt && <small>{formatDate(evidence.createdAt)}</small>}</article>) : <p className={styles.muted}>Ingen resultatbevis er knyttet til oppgaven.</p>}</div><button className={styles.secondaryButton} onClick={() => onOpenTask(task)}>Åpne oppgaven i MC ↗</button><EvidenceForm key={task.id} task={task} onSaved={onRefresh} onOpenNote={onSelect} /></> : <>
        {note && <><div className={styles.metaLine}><span>{projectNames[note.projectKey]}</span><span className={styles.tag}>{kindNames[note.kind]}</span></div><h3 className={styles.inspectorTitle}>{note.title}</h3><p className={styles.path}>{note.path}</p><dl className={styles.detailList}><div><dt>Dokumentet sist endret</dt><dd>{formatDate(note.modifiedAt)}</dd></div><div><dt>Kildedato</dt><dd>{note.sourceDate ? formatDate(note.sourceDate) : 'Ikke oppgitt i kilden'}</dd></div></dl><p className={styles.freshnessNote}>Endringstid viser filens ferskhet. Den bekrefter ikke at alle påstander fortsatt er riktige.</p>{note.tags.length > 0 && <div className={styles.tags}>{note.tags.map(tag => <span key={tag}>#{tag}</span>)}</div>}</>}
        {noteResource.loading && !noteResource.data && <p className={styles.loading} role="status">Leser dokumentet …</p>}
        {noteResource.error && <div className={styles.error} role="alert"><strong>Dokumentet kunne ikke leses</strong><p>{noteResource.error}</p>{noteResource.data && <p>Innholdet nedenfor er fra siste vellykkede henting.</p>}<button className={styles.textButton} onClick={onRefresh}>Prøv igjen</button></div>}
        {noteResource.data && <div className={styles.noteReader}><ReactMarkdown remarkPlugins={[remarkGfm]} components={{ img: ({ alt }) => <span className={styles.muted}>[Bilde i originalkilden{alt ? `: ${alt}` : ''}]</span>, a: ({ href, children }) => safeExternalUrl(href) ? <a href={safeExternalUrl(href)} target="_blank" rel="noopener noreferrer" referrerPolicy="no-referrer">{children}</a> : <span>{children}</span> }}>{markdownBody(noteResource.data.content)}</ReactMarkdown></div>}
        {note && <button className={styles.button} onClick={() => onCreate(note)}>Lag oppgave fra denne kilden <span aria-hidden="true">→</span></button>}
      </>}
      <div className={styles.detailSection}><h4>Registrerte forbindelser</h4>{relations.length ? relations.map((link, index) => { const target = items.find(candidate => candidate.id === (link.source === selected ? link.target : link.source)); return target ? <button className={styles.relation} key={index} onClick={() => onSelect(target.id)}><small>{link.source === selected ? 'Utgående' : 'Inngående'} · {relationNames[link.kind]}</small><span>{target.title} ↗</span></button> : null }) : <p className={styles.muted}>Ingen forbindelser i det lastede utvalget. Det betyr ikke at dokumentet aldri er brukt.</p>}</div>
    </div>}
  </aside>
}
